### ISSUE TITLE
Specify a stack with a sidewall angle

### ISSUE THREAD

**Issue by smartalecH** [facebookresearch/fmmax#25]
Currently, if one wants to simulate a structure that exhibits a sidewall angle, then one must slice the geometry into a "wedding cake" manually. It would be great if we could automate this procedure via an API hook.

Similarly, it might be worth investigating how straightforward it would be to cache several different wedding cake layers (even if they aren't currently used), that way one could optimize the global thickness of the stack (or even the angle itself) without recomputing new eigenmodes each iteration.

**Comment by drinwater** [comment]
Would gdsfactory's Layerstack be useful here? IIRC we can add sidewall angles in it

-SkandanC

**Comment by smartalecH** [comment]
Thanks Skandan! 

> Would gdsfactory's Layerstack be useful here?

Hmm possibly, but I don't think so.

The intent (IIRC) behind [`Layerstack`](https://github.com/gdsfactory/gdsfactory/blob/4ea9a0892d6bb8280046ce55a91c10cfc20739c1/gdsfactory/technology/layer_stack.py#L74) is to take a series of gds lithography layers and build a simulation out of them. Like you say, you can add sidewall angles, but that's not quite what we want to accomplish here.

Rather, we often have some predefined curve/function (a simple one being a diagonal line, corresponding to a simple sidewall angle) that describes the vertical (e.g. z-direction) nature of some structure. With `fmmax`, we need to discretize that curve in the z-direction (i.e. create. wedding cake from it). So the hard part here, is efficiently taking an analytic representation and discretizing it. And being able to parameterize it. *And* being able to differentiate through it.

**Comment by mfschubert** [comment]
After a bit of thought, it seems that a basic version of this is not actually too challenging.

I implemented a version of this in the `discrete_profile_layer_thicknesses` function in the `microlens_array` example added in https://github.com/facebookresearch/fmmax/pull/31.

It turns out to be a relatively small amount of code. It is fairly but not fully general (e.g. it requires a monotonically _increasing_ profile, where in some cases we may desire a _decreasing_ profile). It should be fairly easy to make adaptations to whatever specific case a user may have. Given this, I think we will opt to keep this type of code together with examples, rather than adding it as a part of the core fmmax simulator.

**Comment by mfschubert** [comment]
Closing this since https://github.com/facebookresearch/fmmax/pull/31 is now merged.

As a final note, there should be no extra work in avoiding repeated eigendecompositions; we simply need to perform these in the context of `jax.ensure_compile_time_eval()`.
